### ISSUE TITLE
catkin_make failure: loopWorkerThread not declared

### ISSUE THREAD

**Issue by MathieuR** [dxydas/ros-bioloid#2]
Hi Dimitris,

Thanks for your work on this.
I ran into the following issue trying to compile it with catkin_make:
bioloid_master/src/rosworker.cpp:26:9: error: ‘loopWorkerThread’ was not declared in this scope
     if (loopWorkerThread != NULL)

Regards,
-Mathieu

**Comment by dxydas** [comment]
Fixed! That was an old var which had to be removed.
Please bear in mind that the GUI is in a work-in-progress state so it will be updated periodically.

Regards,
Dimitris

**Comment by MathieuR** [comment]
I totally understand, no worries and thanks for the quick fix.
I will try to keep in sync with the latest and if I find a bug, I will try to send you PR.

What is your plan for the future? is splitting the three directory into separate repo on the TODO list :)

Regards,
-Mathieu

**Comment by dxydas** [comment]
Thanks!
I've kept this repo as one as it's all the ROS tools for my robot together, might split them off later on.
